import { createHash } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const DEFAULT_ROOT = fileURLToPath(new URL('../portfolio/public/gym/', import.meta.url));

function excluded(name) {
  return name.startsWith('.') || ['sw.js', 'precache.js', 'test', 'tests', '__tests__'].includes(name) || /(?:^|\.)(?:test|spec)\.[cm]?jsx?$/.test(name);
}

async function assetFiles(root, relative = '') {
  const entries = await readdir(path.join(root, relative), { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    if (excluded(entry.name)) continue;
    const name = path.join(relative, entry.name);
    if (entry.isDirectory()) files.push(...await assetFiles(root, name));
    else if (entry.isFile()) files.push(name.split(path.sep).join('/'));
    else throw new Error(`Gym assets must be local regular files: ${name}`);
  }
  return files.sort();
}

export async function prepareGym(directory = DEFAULT_ROOT) {
  const root = path.resolve(directory);
  const files = await assetFiles(root);
  const fileSet = new Set(files);
  for (const required of ['index.html', 'app.mjs', 'styles.css', 'data.mjs', 'store.mjs', 'manifest.webmanifest']) {
    if (!fileSet.has(required)) throw new Error(`Missing required gym asset: ${required}`);
  }
  const dataSource = await readFile(path.join(root, 'data.mjs'));
  const dataVersion = createHash('sha256').update(dataSource).digest('hex');
  const data = await import(`${pathToFileURL(path.join(root, 'data.mjs')).href}?version=${dataVersion}`);
  if (!Array.isArray(data.EXERCISES)) throw new Error('Gym data must export an EXERCISES array.');
  for (const exercise of data.EXERCISES) {
    for (const field of ['media', 'poster', 'gif']) {
      const reference = exercise[field];
      if (reference === '' || reference === undefined || reference === null) continue;
      if (typeof reference !== 'string' || /^(?:[a-z][a-z\d+.-]*:|[\/\\])/i.test(reference) || /[?#\\]/.test(reference)) {
        throw new Error(`Exercise ${exercise.id || ''} ${field} must reference a local media file: ${reference}`);
      }
      let decoded;
      try { decoded = decodeURIComponent(reference); }
      catch { throw new Error(`Invalid local media path: ${reference}`); }
      const resolved = path.resolve(root, decoded);
      const relative = path.relative(root, resolved).split(path.sep).join('/');
      if (relative.startsWith('../') || path.isAbsolute(relative) || !fileSet.has(relative)) {
        throw new Error(`Exercise ${exercise.id || ''} ${field} references missing or outside media: ${reference}`);
      }
    }
  }
  const hash = createHash('sha256');
  for (const file of [...files, 'sw.js']) {
    hash.update(file).update('\0').update(await readFile(path.join(root, file))).update('\0');
  }
  const version = hash.digest('hex').slice(0, 20);
  const assets = files.map(file => `./${file.split('/').map(encodeURIComponent).join('/')}`);
  await writeFile(path.join(root, 'precache.js'), `// Generated by scripts/prepare-gym.mjs.\nself.GYM_VERSION = ${JSON.stringify(version)};\nself.GYM_ASSETS = ${JSON.stringify(assets, null, 2)};\n`);
  return { version, assets };
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  try {
    const { version, assets } = await prepareGym(process.argv[2]);
    console.log(`Prepared gym offline version ${version} with ${assets.length} local assets.`);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
